#version 430

layout(local_size_x = 16, local_size_y = 16) in;

struct Body {
    vec4 pos; // xyz + mass
};

layout(std430, binding = 1) buffer Bodies {
    Body objects[];
};

layout(std430, binding = 0) buffer Grid {
    vec4 gridVertices[];
};

uniform float size;
uniform int divisions;
uniform int bodyCount;

void main() {
    ivec2 id = ivec2(gl_GlobalInvocationID.xy);

    if (id.x > divisions || id.y > divisions) return;

    int index = id.y * (divisions + 1) + id.x;

    float step = size / float(divisions);

    float x = -size * 0.5 + id.x * step;
    float z = -size * 0.5 + id.y * step;

    float y = 0.0;

    for (int i = 0; i < bodyCount; i++) {
        vec3 d = vec3(x, 0.0, z) - objects[i].pos.xyz;

        float r2 = dot(d, d) + 1e-6;
        float r = sqrt(r2);

        y += -5e7 * (objects[i].pos.w / r);
    }

    gridVertices[index] = vec4(x, y, z, 1.0);
}